site_name: Matt Lafferty

theme:
  name: material
  icon:
    admonition:
      note: octicons/infinity-16
      quote: octicons/quote-16

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: "home.md"
  - Mathematics:
    - Calculus: 'calc.md'
    - Analysis:
      - The Natural Numbers: 'mathematics/analysis/natural_numbers.md'
      - Induction: 'mathematics/analysis/induction.md'
